export const DEFAULT_CHART = [
  { code: "1101", name: "Cash Register", type: "asset", subtype: "cash" },
  { code: "1102", name: "Bank Accounts", type: "asset", subtype: "bank" },
  { code: "1103", name: "Petty Cash", type: "asset", subtype: "cash" },
  { code: "1201", name: "Inventory Stock", type: "asset", subtype: "inventory" },
  { code: "1301", name: "Accounts Receivable", type: "asset", subtype: "receivable" },
  { code: "2101", name: "Vendor Payables", type: "liability", subtype: "payable" },
  { code: "2201", name: "Tax Payable", type: "liability", subtype: "tax" },
  { code: "2301", name: "Staff Salaries Payable", type: "liability", subtype: "payroll" },
  { code: "4101", name: "Food Sales", type: "income", subtype: "sales" },
  { code: "4102", name: "Beverage Sales", type: "income", subtype: "sales" },
  { code: "4103", name: "Delivery Revenue", type: "income", subtype: "sales" },
  { code: "4104", name: "Service Charges", type: "income", subtype: "sales" },
  { code: "4105", name: "Sales Discounts", type: "expense", subtype: "contra" },
  { code: "5101", name: "Cost of Goods Sold", type: "expense", subtype: "cogs" },
  { code: "5201", name: "Food Purchases", type: "expense", subtype: "purchase" },
  { code: "5202", name: "Utility Bills", type: "expense", subtype: "operating" },
  { code: "5203", name: "Rent", type: "expense", subtype: "operating" },
  { code: "5204", name: "Salaries", type: "expense", subtype: "payroll" },
  { code: "5205", name: "Marketing", type: "expense", subtype: "operating" },
  { code: "5206", name: "Maintenance", type: "expense", subtype: "operating" },
  { code: "5207", name: "Waste & Spoilage", type: "expense", subtype: "inventory" },
  { code: "3001", name: "Owner Equity", type: "equity", subtype: "equity" },
] as const;
